name: Build

on: push

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build all
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*

  upload_all:
    needs: [ build ]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: build-artifacts
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1